DESCRIPTIONS_ = {
    "acronym_identification": "In the following sentence, an acronym is identified. You must answer the expansion (acronym meaning) of the acronym in question. ",  # ME ,
    "ade_corpus_v2-classification": "Is the following text related to adverse drug effect (ADE) ?. Answer with 'Related', or 'Not Related'. ",
    "ade_corpus_v2-dosage": "Read the following text. What is the dosage of the drug mentioned ?",
    "ade_corpus_v2-effect": "In the following text, what is the effect of the drug in question ?",
    "adversarialqa": "Answer the following question from the following context. ",
    "aeslc": "Given the following email body, generate a subject line. ",
    "ag_news": "Would the following news article appear in the 'Sci/Tech', 'Sports', 'World' or 'Business' section ? ",
    "ai2_arc": "I am hesitating between 4 options to answer the following question, which option should I choose? Return the string of the correct option, not the option A,B,C,D. ",
    "amazon_polarity": "You are given a review. What is the overall sentiment of this review ? Answer with 'positive' or 'negative'.", # ME
    "anli": "Given the following premise and hypothesis, would you say they are a contradiction, an entailment or neutral ?",
    "app_reviews": "On a scale of 1-5 (with 1 being least favorable and 5 being most favorable), how would you rate this review?. Answer with '1', '2', '3', '4', or '5'. ",
    "aqua_rat": "'You will now be given a question and a set of options. Choose the correct option. Return the string of the correct option, not the option A,B,C,D. ",
    "art": "You know the following two observations. Which of the hypotheses is more believable ?. Answer with 'hypothesis 1', or 'hypothesis 2'. ",
    "aslg_pc12": "Convert the following english sentence to American Sign Language Gloss",   # None
    "biomrc": "You are given a question with a word replaced by XXXX. Choose which @entity in the text should replace XXXX.", # None, but doable
    "blimp-anaphor_gender_agreement": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ", # None, but doable
    "blimp-anaphor_number_agreement": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ", 
    "blimp-determiner_noun_agreement_with_adj_irregular_1": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ", 
    "blimp-ellipsis_n_bar_1": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'.",
    "blimp-ellipsis_n_bar_2": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'.",
    "blimp-existential_there_quantifiers_1": "You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'.",
    "blimp-irregular_past_participle_adjectives":"You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ",
    "blimp-sentential_negation_npi_licensor_present":"You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ",
    "blimp-sentential_negation_npi_scope":"You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'. ",
    "blimp-wh_questions_object_gap":"You are given two sentences. Choose which one is correct. Answer with 'sentence 1' or 'sentence 2'.  ",
    "boolq":"You are given a question along with some context. Answer with 'yes' or 'no'.", # None, but doable
    "break-QDMR": "You are given a question. Can you describe the steps you should take to answer it, where at each step you return a piece of information?",  # None
    "break-QDMR-high-level": "You are given a question. Describe the steps you should take to answer it, where at each step you can select from items returned in previous questions.",  # None 
    "circa": "Given the question-answer pair of X and Y, which of the following answers is Y implying ? Choose between 'In the middle, neither yes nor no', 'No', 'Other', 'Yes', 'Yes, subject to some conditions'. ",  
    "climate_fever": "You are given a statement. Would you say this statement is 'Disputed', 'Not enough info', 'Refutes' or 'Supports' ?",  # MISSING EVIDENCE
    "codah": "Given a prompt and four completions, select the completion that is the most plausible in continuing or answering the prompt. This task is designed to test common sense and has various categories ranging between idioms, negated statements, polysemy, subject referencing, and quantitative reasoning. Generate either Completion A, Completion B, Completion C, or Completion D. Return the string of the correct option, not (A) or A.",  # AS dataset
    "common_gen": 'In this task, you are given concept set (with 3 to 5 concepts) that contain mentions of names of people, places, activities, or things. These concept sets reflect reasonable concept co-occurrences in everyday situations. All concepts given as input are separated by "#". Your job is to generate a sentence describing a day-to-day scene using all concepts from a given concept set.', # AS dataset
    "commonsense_qa": 'You are given a question and some answer options (associated with "A", "B", "C", "D"). You should choose the correct answer based on commonsense knowledge. Avoid answering questions based on associations, the set of answers are chosen deliberately to capture common sense beyond associations. Return the string of the correct option, not (A) or A',  # AS dataset
    "cos_e": None,  # This task makses no sense. 
    "cosmos_qa": 'Read the following statement. Then, choose the appropriate answer. Return the string of the correct option, not (A) or A', # Mine 
    "crawl_domain": 'You are given a string without spacing or capitalization. Read the string and generate the same string with appropriate spacing and capitalization',  # Mine
    "crows_pairs": "You are given two sentences. Select the sentence which contains a stereotype. Answer with 'sentence 1' or 'sentence 2'.", 
    "dbpedia_14": "In this task, you are given a text which is the body of a document. Your job is to classify the topic of the document into these categories: Company, Educational Institution, Artist, Athlete, Office Holder, Mean of transportation, Building, Natural place, Village, Animal, Plant, Album, Film, Written work. Your output should be the category without spaces", 
    "definite_pronoun_resolution": "You are given a sentence, followed by a pronoun contained in the sentence, and finally 2 possible candidates for which the pronoun refers to. Choose the appropriate choice. ", 
    "discovery": "You are given two sentences. Write the discourse marker that should link the two sentences together.", 
    "dream": "'In this task, you will be shown a conversation and a question. You should categorize the question into matching, summary, logic, arithmetic and, commonsense groups. Matching is a question entailed or paraphrased by exactly one sentence in a dialogue. The answer can be extracted from the same sentence. Questions that cannot be answered by the surface meaning of a single sentence belong to the reasoning category. We further define summary, logic, arithmetic and, commonsense subcategories. Answering summary questions requires the whole picture of dialogue, such as the topic of dialogue and the relation between speakers. We require logical reasoning to answer logical questions. in arithmetic questions Inferring the answer requires arithmetic knowledge. To answer commonsense questions, besides the textual information in the dialogue, we also require additional commonsense knowledge that cannot be obtained from the dialogue. Note that a question can be in more than one group. 'W' and 'M' in the conversations stand for 'woman' and 'man'.", # AS DS
    "duorc": 'In this task, you will be shown an extract from a movie plot and a question. You need to provide the correct answer for it. Short answers containing words that are present in the passage are preferred.',  # AS DS
    "e2e_nlg_cleaned": 'In this task, we ask you convert a data table of restaurant descriptions into fluent natural-sounding English sentences. The input is a string of key-value pairs; the output should be a natural and grammatical English sentence containing all the information from the input.',  # AS DS
    "eli5-askh": "You are given a question written by a user on Reddit, along with some motivation and / or context. You must predict answers given by other users.", # Mine
    "eli5-asks":"You are given a question written by a user on Reddit, along with some motivation and / or context. You must predict answers given by other users.", # Mine
    "eli5-eli5":"You are given a question written by a user on Reddit, along with some motivation and / or context. You must predict answers given by other users.", # Mine
    "emo": 'In this task you will be given some text dialogue and you need to infer the underlying emotion of the text. The possible emotions are happy, sad, angry, or other.',  # AS DS
    "emotion": "In this task, you are given a sentence containing a particular emotion. You must classify the sentence into one of the six emotions: 'joy', 'love', 'anger', 'fear', 'sadness' or 'surprise'.",  # AS DS
    "empathetic_dialogues": "You are given a sentence, followed by an emotion. Generate a dialogue based on the given sentence, with the tone of the given emotion.",  # Me
    "ethos-directed_vs_generalized": "You are given a piece of hateful text. You must classify the hate as 'directed' towards a specific individual, or 'genealized' towards a community",  # ME
    "ethos-disability": "You are given a piece of text. Your task is to classify the text based on whether a person or group of people are receiving hate based on a disability. If there is a hate based on a disability in the text, answer with 'true', otherwise, answer with 'false'.",  # Me
    "ethos-gender": "You are given a piece of text. You should find out if there are any gender specific criticized comments. Label the text as 'true' is there is gender criticism, otherwise 'false'",  # AS DS 
    "ethos-national_origin": "You are given a piece of text. You should determine of these is hate based on national origin. Answer 'true' if there is hate based on nationality, else 'false'.",  # AS DS
    "ethos-race": "You are given a piece of text. You should determine of these is hate based on race. Answer 'true' if there is racial hate, else 'false'.", 
    "ethos-religion" : "You are given a piece of text. Your task is to classify the text based on whether a religion or a person/group of people are receiving hate based on religion. If there is a hate based on religion in the text, answer with 'true', otherwise, answer with 'false'.", 
    "ethos-sexual_orientation": "You are given a piece of text. Your task is to classify the text based on whether a person or a person/group of people are receiving hate based on sexual orientation. If there is a hate based on sexual orientation in the text, answer with 'true', otherwise, answer with 'false'.",  # all ethos derived from AS DS
    "financial_phrasebank": "Classify the given a piece of financial news into three classes: positive, negative, and neutral. Output must be 'positive', 'negative', or 'neutral'.",  # AS DS, but I am MISGGIN THIS DATA
    "freebase_qa": 'Given a trivia question precisely answer the question with a word/phrase/name. External resources such as Wikipedia could be used to obtain the facts.',  # AS DS
    "gigaword": 'In this task, you are given a text of the article. Your task is to generate a headline (title) for this article.',  # AS DS
    "glue-cola": "You will be given a sentence. Check whether the sentence is grammatically correct and is meaningful. If the sentence is grammatically correct, then answer with 'acceptable', otherwise answer with 'unacceptable'.",  # AS
    "glue-mnli": "You are given a premise sentence and an hypothesis sentence. Answer 'contractiction' if the hypothesis contradicts the premise, 'entailment' if the hypothesis entails the premise, or 'neutral' otherwise.",  # ME
    "glue-mrpc":'You are given two sentences(Sentence1 and Sentence2). Answer "equivalent" if these sentences are a paraphrase of one another, otherwise answer "not_equivalent".',  # AS DS
    "glue-qnli": "you are given a question and a sentence. if the sentence entails the question, answer 'entailment'. otherwise answer 'not_entailment'. ",  # mine
    "glue-qqp": "You are given two sentences. If the two sentences convey the same meaning, answer 'duplicate'. Otherwise answer 'not_duplicate'.",  # Mine
    "glue-rte": "You are given two sentences. If the second sentence entails the first sentence, answer 'entailment'. Otherwise answer 'not_entailment'.",  # Mine 
    "glue-sst2": "You are given a statement. Answer 'positive' if the overall sentiment of the sentence is positive, otherwise answer 'negative'.", 
    "glue-wnli": "You are given two sentences. If they convey the same information, answer 'entailment', otherwise answer 'not_entailment'. ",  # NOT ENTAILMENT ?
    "google_wellformed_query":"Read the given query and classify it as a 'well-formed' or 'not well-formed' query depending on how well the query is formed, 'not well-formed' being the expected output for a not so well formed query and 'well-formed' being the expected output for a well formed query. A query may be wrong based on common sense or general facts, but if it is well formed, you should answer with well-formed.", 
    "hate_speech18": "Read the following sentence. Does the sentence contain hate speech ? If yes, answer with 'hate'. If it does not contain hate speech, answer with 'noHate'.",  #PS
    "hate_speech_offensive": "Classify the given tweet into the three categories: (1) 'hate speech', (2) 'offensive language' and (3) 'neither'. 'hate speech' is kind of a threating statement or sometimes include call for violence while 'offensive language' statement just offensds someone. 'neither' is when it doesn't fall into hate speech or offensive category.",  # AS DS
    "hatexplain": 'The input is a tweet which can be classified as Hate Speech, Offensive or Normal. Given such a tweet, output the class the tweet belongs to. Hate Speech will contain threatening language towards the community targeted. Offensive language will contain abusive or discriminatory language towards the community targeted.',  # AS DS  [output not formatted]
    "health_fact": None, # MISSING THE CONTEXT WITH WHICH TO ANSWER QUESTION
    "hellaswag": 'In this task, you are given a context and four options. Each option is a suggested ending for the context. You should read the context and pick the best ending for the context. Please answer with the text that if followed after the correct letter', # "A", "B", "C", and "D". '
    "hotpot_qa": 'In this task, you are given a set of context paragraph and some supporting facts to answer a question. Your task is to generate answer for given question based on set of context paragraphs and supporting facts.', # AS DS
    "imdb": 'In this task, you are given a review of movie. Your task is to classify given movie review into two categories: 1) positive, and 2) negative based on its content.', #AS DS
    "jeopardy": 'You will be given a trivia clue, and the category it belongs to. You should answer with the best answer that belongs in the category and is described by the clue.', # AS DS
    "kilt_ay2": "You are given a news article. Inside the article there is an entity delimitited by [START_ENT] and [END_END]. You must identify this entity.", # ME
    "kilt_fever": "You are given a sentence. If the statement if true, answer 'SUPPORTS'. Otherwise, answer 'REFUTES'.", # ME
    "kilt_hotpotqa": 'In this task, you are given a question. You have to answer the question based on your information.', # AS DS
    "kilt_nq": "The goal is to predict an English answer string for an input English question. All questions can be answered using the contents of English Wikipedia.", # PS [WEIRD FORMATTING ON OUR END|
    "kilt_trex": "You are given a base entity, along with requested relation for this entity. You must answer the correct entity which correctly relates to the base entity.", # ME 
    "kilt_wow": "You are given a dialogue. The last sentence ends with a question, and you must attempt to answer how the participants in the dialogue would answer it.", # ME 
    "kilt_zsre": "You are given a base entity, along with requested relation for this entity. You must answer the correct entity which correctly relates to the base entity.", # ME
    "lama-conceptnet": "You are given a sentence about a concept where one word is masked. You must answer the missing word.",
    "lama-google_re": "You are given a sentence about historical people. Either their place of birth or year of birth is masked out. From the context you must infer which of the year of place of birth to answer, and then provide the appropriate answer.", # Me
    "lama-squad":"You are given a sentence about a concept where one word is masked. You must answer the missing word.",
    "lama-trex":"You are given a sentence about a concept where one word is masked. You must answer the missing word.",
    "liar": "You are given a statement, along with relevant context, and information on the speaker. You must determine how true the statement is. The possible answers, ranked from least true to most true, are 'pants-fire', 'false', 'barely-true', 'half-true', 'mostly-true', or 'true'.", # ME
    "limit": "In this task, you are given a sentence and your task is to identify whether the sentence contains motion or not, by identifying the entities in motion. The sentence contains motion if it (i) involves the movement of a physical object. (ii) contains v. Sometimes there can be verb which indicates a motion but the motion might have happened in the past and this is equivalent to no motion. For example, if objects A and person B are in motion, your answer should be of format 'A [SEP] B'. ", # AS DS but me
    "math_qa": "Given a math problem with context and a question and 5 answer choices, the task is to provide the correct answer choice based on the problem. You must choose one of the given answer choices. For example, if the choices are a) 1$ and b) 2$ and the correct answer is a), then you must answer '1$'. ", # AS DS but me
    "mc_taco": 'Given the context, the question, and the candidate answer, the task is to determine whether the candidate answer is plausible ("yes") or not ("no").', # PS. weird / hard
    "medical_questions_pairs": "In this task you are given a medical question pair hand-generated. Your task is to classify a given post into two categories 1) 'Similar' if the given two questions have a same connotation 2) 'Dissimilar' if the given two questions have a different connotation or meaning.", # AS DS
    "mocha": "Output the similarity value between 1.0 (completely different) and 5.0 (identical) for Sentence A and B. Answer choices are '1', '2', '3', '4', or '5'. ", # PS
    "multi_news": 'In this task, you are given a text of many news articles seperated by special token "|||||". Your task is to summarize them.', # AS DS
    "numer_sense": "Given a sentence, fill out the missing word with a 'no' or a number (between zero and ten). You should write the numbers with english alphabet, like: four instead of 4.",
    "onestop_english": "How would you assess the reading difficulty of the text passage below? Choose from one of 'elementary'. 'intermediate' or 'advanced' levels.", # PS
    "openbookqa": "In this task, you are given a multiple-choice question and you have to pick the correct option. If the answer choices are a) 10 and b) 20 and the correct answer is a), then you must answer '10'. ", # AS DS but me
    "paws": "You are given two sentences. Are the sentences equivalent ? In other words, do they convey the same meaning ? Answer '1' if they do, or '0' if they do not.", # ME
    "piqa": "In this task the focus is on physical knowledge about the world. You are given a goal, along with two possible solutions. You must choose the appropiate solution to accomplish the goal. Your answer should be either 'solution 1' or 'solution 2'.", # Me
    "poem_sentiment": "In this task, you need to identify the sentiment of the given sentence as one of 'positive', 'negative', 'mixed', or 'no impact' if the sentiment is neutral'. ", # ME
    "proto_qa": 'Write a correct answer for the question. You should reason about prototypical situations and provide the correct answer. Avoid answers that provide incomplete justification for the question.', # AS DS
    "qa_srl": 'In this task, you are given a sentence and question which can be answered using the sentence. Your task is to answer the question using the information from the sentence. The answer to the question is unique and it is a continuous text span from the sentence.', # AS DS
    "qasc": "Write a correct answer to the given question based on its associated fact. Make sure that your answer is contained in the associated fact. Don't be creative and introduce any new word that is not mentioned in the associated fact! Remember that the associated fact has been rearranged to form the question. So, the correct answer words must lie within the associated fact. The correct answer can be a word, phrase, or even a sentence. If the answer choices are a) 10 and b) 20 and the correct answer is a), then you must answer '10'.", 
    "quail": "You are given a question followed by possible answers to this question. Finally, you are given a context passage containing the answer. If the answer choices are a) 10 and b) 20 and the correct answer is a), then you must answer '10'.", # me  
    "quarel": "You are given a sentence and a question. You're expected to write the correct answer based on the sentence. If the answer choices are a) 10 and b) 20 and the correct answer is a), then you must answer '10'. ", # Me 
    "quartz-no_knowledge": 'You are given a question or fill-in-the-blank question, two answer options (Option1 and Option2) and an Explanation. Your task is to find the correct answer (return the string of the correct option, not option1/2) for the given question from the given options.', # AS DS
    "quartz-with_knowledge":'You are given a question or fill-in-the-blank question, two answer options (Option1 and Option2) and an Explanation. Your task is to find the correct answer (return the string of the correct option, not option1/2) for the given question from the given options and using explanation.', # AS DS
    "quoref": "In this task, you're expected to write answers to questions involving multiple references to the same entity. The answer to the question should be unambiguous and a phrase in the paragraph. Most questions can have only one correct answer.", # AS DS 
    "race-high": 'You are given a question or fill-in-the-blank question, several answer options, and an context paragraph containing the answer. Your task is to find the correct answer (return the string of the correct option, (not (A) or B) for the given question from the given options.', # copied
    "race-middle": 'You are given a question or fill-in-the-blank question, several answer options, and an context paragraph containing the answer. Your task is to find the correct answer (return the string of the correct option, (not (A) or B) for the given question from the given options.', # copied
    "reddit_tifu-title":'In this task, you are given a Reddit post as a text. Your task is to generate a title for this text. The title should contain the situation that caused humor. The title should contain 7-12 words, ideally.', # AS DS
    "reddit_tifu-tldr": 'In this task, you are given a Reddit post as a text. Your task is to generate a short summary for this text. The summary must include a situation which caused humor. The summary should be one or two sentences long.', # AS DS
    "ropes": 'You are given a background paragraph that describes one or more causal or qualitative relationships such as a relationship in economics or a scientific law and a story that makes use of the concepts or the relationship described in the provided paragraph. You are also given a question about the story that requires an understanding of the relationship described in the background paragraph and the story. You need to come up with an answer to the given question; the answer will be a span from either the question or the story. In order to correctly answer the given question, you need to understand the relationship mentioned in the background paragraph and should be able to use it to understand that in the story. Your answer can not consist of any word that is not mentioned in any of these: the background paragraph, the story, or the question. You can directly copy and paste a span from the story or the question while answering the given question.', # AS DS
    "rotten_tomatoes": "You are given a movie review. Answer 'positive' if the overall sentiment of the review is positive, otherwise answer 'negative'.", # me
    "samsum": 'In this task, you are given a conversation, and your task is to generate a summary from the information present in the given conversation. Generate a summary in such a way that the context should be present in the conversation. It should cover the complete context of the conversation. ', # AS DS
    "scicite": "You are given an excerpt from a scientific paper. You must determine if this excerpt presents background work, results, or described the method in the paper. Acceptable answers are 'method', 'background', and 'result'.", # Me
    "sciq": 'You are given a question or fill-in-the-blank question, several answer options, and an context paragraph containing the answer. Your task is to find the correct answer (return the string of the correct option, (not (A) or B) for the given question from the given options.', # copied
    "scitail": "In this task, you are given two statements. The task is to output whether a given textual premise, i.e. Statement 2, entails or implies a given scientific fact, i.e. Statement 1. The output should be 'entailment' if Statement 2 supports Statement 1 and should be 'neutral' otherwise.", # AS DS
    "search_qa":'Given a trivia question precisely answer the question with a word/phrase/name. External resources such as Wikipedia could be used to obtain the facts.', # copied, AS DS
    "sick": "In this task, you're given a pair of sentences, sentence 1 and sentence 2. Your job is to choose whether the two sentences clearly agree (entailment)/disagree (contradiction) with each other, or if this cannot be determined (neutral). Your answer must be either 'entailment', 'neutral', or 'contradiction'.", # AS DS
    "sms_spam": "In this task, you're given text messages in natural language. Your task is to classify those text messages based on their content into two classes: (1) Spam and (2) Ham messages. If the content of the given message is irrelevant to the receiver or is equally relevant to many other potential recipients then it must be labeled as ‘spam’, otherwise, it should be labeled as ‘ham’.", # AS DS
    "social_i_qa": "In this task, you're given a context, a question, and three options. Your task is to find the correct answer to the question using the given context and options. Also, you may need to use commonsense reasoning about social situations to answer the questions. Return the string of the correct option, not (A) or A.", # AS DS  
    "spider": "You are given a question. Your task is to create a valid SQL query which returns the answer the the question in the text. Your output should contain SQL keywords like 'SELECT' and 'FROM'. ", # ME
    "squad-no_context": "You are given a question. Your task is to answer the question using natural language.", # ME 
    "squad-with_context": "You are given a question, and a context. You task is to read the context to find the answer to the question, and return the answer.", # ME
    "superglue-cb" : "Given the following premise and hypothesis, would you say they are a contradiction, an entailment or neutral ?", # copy
    "superglue-copa": 'In this task, you are given a premise sentence, two possible options and a question word. If the question was cause you should select the option that is a possible cause of the premise sentence, and if the question word was effect you should find the option which is a possible effect of the premise sentence. Return the string of the correct option, not (A) or A.', # AS DS  
    "superglue-multirc": 'You are given a paragraph, a question and some answer options (associated with "A", "B", "C", "D", etc.) You need to list all the correct answer options with their associated letters (e.g. "A" can be a valid answer). Note that sometimes, more than one option can answer the question correctly and completely. In those cases, please generate all such options separated by [SEP]. Return the string of the correct option, not (A) or A.', # AS DS  
    "superglue-record": "In this task, you are presented with a passage where an entity has been replaced by '@placeholder'. You must read the passage and determine who the placeholder tag is referring to. Return this answer.", # ME
    "superglue-rte": "You are given a question and a sentence. if the sentence entails the question, answer 'entailment'. otherwise answer 'not_entailment'. ",  # mine
    "superglue-wic": "In this task, you are given a word, followed by two sentences. Your task is to figure out whether both the sentences use the aforementioned word with the same meaning. You should respond with 'true' if the words in both sentences share the same meaning, and 'false' otherwise.", # AS DS
    "superglue-wsc": None,
    "swag": 'In this task, you are given a context and four options. Each option is a suggested ending for the context. You should read the context and pick the best ending for the context. Return the string of the correct option, not (A) or A.',
    "tab_fact": "You are given a statement, followed by tabular data. By looking at the data, you must determine whether the original statement is refuted or entailed. Answer choices are 'refuted' or 'entailed'. ", # Me 
    "trec": "You are given a question. You need to detect which category better describes the question. A question belongs to the description category if it asks about description and abstract concepts. Entity questions are about entities such as animals, colors, sports, etc. Abbreviation questions ask about abbreviations and expressions abbreviated. Questions regarding human beings, description of a person, and a group or organization of persons are categorized as Human. Quantity questions are asking about numeric values and Location questions ask about locations, cities, and countries. Answer with 'DESC' for descriptions, 'ENTY' for entity', 'ABBR' for abbreviation, 'HUM' for person, 'NUM' for quantity, and 'LOC' for Location.", # AS DS 
    "trec-finegrained": 'You are given a question. You need to detect which category better describes the question. A question belongs to the description category if it asks about description and abstract concepts.', # AS DS, won't work in 0-shot 
    "tweet_eval-emoji": "You are given a tweet. You need to select which emoji is the most appropriate for the tweet. Valid emojies are ['☀', '✨', '❤', '🇺🇸', '🎄', '💕', '💙', '💜', '💯', '📷', '📸', '🔥', '😁', '😂', '😉', '😊', '😍', '😎', '😘', '😜'. ", # ME 
    "tweet_eval-emotion": "You are given a tweet. You must determine the emotion in the tweet. Choose between 'anger', 'joy', 'optimism', 'sadness'.", # ME
    "tweet_eval-hate": "You are given a tweet. You must determine if the conveys hate or not. Choose between 'hate' and 'non-hate'.", # ME 
    "tweet_eval-irony":  "You are given a tweet. Is this an ironic tweet ? Answer with 'irony', or 'non-irony'. ", # ME
    "tweet_eval-offensive":  "You are given a tweet. Is this an offensive tweet ? Answer with 'offensive', or 'non-offensive'. ",
    "tweet_eval-sentiment": "You are given a tweet. You must determinet the overall sentiment of the sweet. Your options are 'negative', 'positive', or 'neutral'. ", # ME 
    "tweet_eval-stance_abortion": "You are given a tweet written on the topic of abortion. You must determine if the person who wrote the tweet supports abortion or not. Answer with 'against' if the tweet is against abortion, 'favor' if the tweet is in favor of abortion, or 'none' otherwise. ", # ME 
    "tweet_eval-stance_atheism":  "You are given a tweet written on the topic of atheism. You must determine if the person who wrote the tweet supports atheism or not. Answer with 'against' if the tweet is against atheism, 'favor' if the tweet is in favor of atheism, or 'none' otherwise. ", # ME 
    "tweet_eval-stance_climate": "You are given a tweet written on the topic of climate change. You must determine if the person who wrote the tweet recognizes the issue of climate change or not. Answer with 'against' if the tweet is against climate change action, 'favor' if the tweet is in favor of climate change action, or 'none' otherwise. ", # ME 
    "tweet_eval-stance_feminist": "You are given a tweet written on the topic of feminism. You must determine if the person who wrote the tweet supports feminism or not. Answer with 'against' if the tweet is against feminism, 'favor' if the tweet is in favor of feminism, or 'none' otherwise. ", # ME 
    "tweet_eval-stance_hillary": "You are given a tweet written on the topic of Hillary Clinton. You must determine if the person who wrote the tweet supports Hillary Clinton or not. Answer with 'against' if the tweet is against Hillary Clinton, 'favor' if the tweet is in favor of Hillary Clinton, or 'none' otherwise. ", # ME 
    "tweet_qa":  'In this task, you are given a context paragraph of the tweet and question. Your task is to generate right answer of given question based on given context tweet paragraph.', # AS DS
    "web_questions": 'A question is presented to you in this task, and your job is to write a potentially correct answer.', # AS DS 
    "wiki_auto": "You are given two sentences. Your goal is to determine if the two sentences are aligned, partially aligned, or not aligned. Answer with 'aligned', 'notAligned', or 'partialAligned'. ", #
    "wiki_bio": 'You are given details about a person. Your goal is to write a short biography based on the using the provided information. ', # ME
    "wiki_qa": 'In this task, you are given a question and an answer. Answer "true" if the given answer correctly answers the question, otherwise answer "false".', # AS DS 
    "wiki_split": 'You are given two sentences. Your goal is to combine them in a single complex sentence. ', # PS 
    "wikisql":"You are given a question. Your task is to create a valid SQL query which returns the answer the the question in the text. Your output should contain SQL keywords like 'SELECT' and 'FROM'. ", # ME
    "wino_grande": 'In this task, you are given a question containing a blank (_) and two options. You should pick the best option to answer the question. Please answer with "A" or "B". You must return the string of the correct option, not option (A) or (B). ', # AS DS  
    "wiqa": 'You are given a question, and a process. How does the supposed perturbation influence the second effect mentioned. Answer by "more", "less" or "no effect".', # PS 
    "xsum": 'In this task, you are given an article. Your task is to summarize the article in a sentence.', # AS DS 
    "yahoo_answers_topics": "You are given a question title. You need to classify it into one of the 10 topics: 0 - 'Society & Culture', 1 - 'Science & Mathematics', 2 - 'Health', 3 - 'Education & Reference', 4 - 'Computers & Internet', 5 - 'Sports', 6 - 'Business & Finance', 7 - 'Entertainment & Music', 8 - 'Family & Relationships', 9 - 'Politics & Government'.", # AS DS  
    "yelp_polarity": 'In this task, you are given Yelp reviews. The task is to classify a review as "positive" if the overall sentiment of the review is positive or as "negative" if the overall sentiment of the review is negative.', # AS DS  
    "yelp_review_full": 'You are given a review about a place. You need to provide a rating from "1" to "5" for this place.', # AS DS 
}

DESCRIPTIONS = {x.strip(): y.strip() if y is not None else None for (x,y) in DESCRIPTIONS_.items()}
