# flan tasks without NIv2 template
FLAN_SUB1 = [
    # "ai2_arc_ARC_Challenge_1_0_0",
    # "dbpedia_14_given_a_choice_of_categories_"
    "ropes_background_new_situation_answer"
]

FLAN_SUB3_with_new = [
    # "bool_q_1_0_0",
    "ai2_arc_ARC_Challenge_1_0_0",
    "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
    "web_questions_whats_the_answer",
]

FLAN_SUB19 = [
    "ai2_arc_ARC_Challenge_1_0_0",
    "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
    "web_questions_whats_the_answer",
    "squad_v1_1_3_0_0",
    "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
    "wiqa_what_might_be_the_first_step_of_the_process",
    "dbpedia_14_given_a_choice_of_categories_",
    "wiqa_effect_with_string_answer",
    "adversarial_qa_dbidaf_answer_the_following_q",
    "duorc_SelfRC_answer_question",
    "quoref_Find_Answer",
    "duorc_ParaphraseRC_answer_question",
    "duorc_ParaphraseRC_title_generation",
    "adversarial_qa_dbidaf_generate_question",
    "yelp_polarity_reviews_0_2_0",
    "dream_baseline",
    "cos_e_v1_11_question_description_option_text",
    "wiki_hop_original_choose_best_object_interrogative_2",
    "quartz_read_passage_below_choose",
]

FLAN_SUB20 = [
    "cos_e_v1_11_generate_explanation_given_text",
    "app_reviews_convert_to_star_rating",
    "trivia_qa_rc_1_1_0",
    "wiqa_effect_with_label_answer",
    "adversarial_qa_dbidaf_tell_what_it_is",
    "super_glue_copa_1_0_2",
    "duorc_ParaphraseRC_extract_answer",
    "quail_context_question_description_text",
    "bool_q_1_0_0",
    "ropes_plain_bottom_hint",
    "cos_e_v1_11_aligned_with_common_sense",
    "sciq_Direct_Question",
    "web_questions_question_answer",
    "quartz_read_passage_below_choose",
    "quoref_Read_And_Extract_",
    "race_middle_Select_the_best_answer_generate_span_",
    "adversarial_qa_droberta_tell_what_it_is",
    "race_high_Select_the_best_answer",
    "wmt16_translate_de_en_1_0_0",
    "ai2_arc_ARC_Challenge_1_0_0",
    "quarel_do_not_use",
]

FLAN_PHI_20 = [
    "app_reviews_generate_review",
    "quail_description_context_question_answer_id",
    "math_dataset_algebra__linear_1d_1_0_0",
    "cos_e_v1_11_explain_why_human",
    "yelp_polarity_reviews_0_2_0",
    "trivia_qa_rc_1_1_0",
    "wiqa_what_might_be_the_last_step_of_the_process",
    "super_glue_multirc_1_0_2",
    "glue_stsb_2_0_0",
    "anli_r1_0_1_0",
    "wiki_bio_guess_person",
    "social_i_qa_Generate_the_question_from_the_answer",
    "race_high_Write_a_multi_choice_question_options_given_",
    "ag_news_subset_1_0_0",
    "web_questions_potential_correct_answer",
    "glue_qqp_2_0_0",
    "quartz_use_info_from_paragraph_question",
    "wiki_hop_original_choose_best_object_affirmative_2",
    "kilt_tasks_hotpotqa_combining_facts",
    "super_glue_rte_1_0_2",
]


# FLAN_TASKS = [
#     "ai2_arc_ARC_Challenge_1_0_0",
#     "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
#     "web_questions_whats_the_answer",
#     "squad_v1_1_3_0_0",
#     "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
#     "wiqa_what_might_be_the_first_step_of_the_process",
#     "dbpedia_14_given_a_choice_of_categories_",
#     "wiqa_effect_with_string_answer",
#     "adversarial_qa_dbidaf_answer_the_following_q",
#     "duorc_SelfRC_answer_question",
#     "quoref_Find_Answer",
#     "duorc_ParaphraseRC_answer_question",
#     "duorc_ParaphraseRC_title_generation",
#     "cot_ecqa",
#     "adversarial_qa_dbidaf_generate_question",
#     "yelp_polarity_reviews_0_2_0",
#     "dream_baseline",
#     "cos_e_v1_11_question_description_option_text",
#     "wiki_hop_original_choose_best_object_interrogative_2",
#     "quartz_read_passage_below_choose",
#     "snli_1_1_0",
#     "true_case",
#     "wiki_qa_Is_This_True_",
#     "dream_answer_to_dialogue",
#     "quoref_Answer_Test",
#     "quail_context_question_description_answer_text",
#     "duorc_ParaphraseRC_generate_question",
#     "wiki_qa_Topic_Prediction_Question_and_Answer_Pair",
#     "web_questions_get_the_answer",
#     "adversarial_qa_dbidaf_tell_what_it_is",
#     "gem_web_nlg_en_1_1_0",
#     "cot_gsm8k_ii",
#     "coqa_1_0_0",
#     "ropes_prompt_beginning",
#     "unified_qa_science_inst",
#     "kilt_tasks_hotpotqa_formulate",
#     "social_i_qa_Generate_answer",
#     "glue_mrpc_2_0_0",
#     "quail_context_description_question_answer_id",
#     "quoref_Guess_Answer",
#     "quail_description_context_question_answer_id",
#     "ropes_background_new_situation_answer",
#     "ropes_prompt_mix",
#     "quac_1_0_0",
#     "cot_ecqa_ii",
#     "wiki_qa_Decide_good_answer",
#     "quoref_Answer_Friend_Question",
#     "quoref_What_Is_The_Answer",
#     "app_reviews_convert_to_rating",
#     "adversarial_qa_dbert_based_on",
#     "cos_e_v1_11_aligned_with_common_sense",
#     "adversarial_qa_dbert_generate_question",
#     "duorc_ParaphraseRC_generate_question_by_answer",
#     "super_glue_cb_1_0_2",
#     "glue_qqp_2_0_0",
#     "web_questions_question_answer",
#     "openbookqa_0_1_0",
#     "wiki_hop_original_choose_best_object_interrogative_1",
#     "stream_qed",
#     "cot_qasc_ii",
#     "anli_r2_0_1_0",
#     "word_segment",
#     "wiki_hop_original_choose_best_object_affirmative_3",
#     "quail_context_question_answer_description_text",
#     "quartz_use_info_from_question_paragraph",
#     "cos_e_v1_11_question_description_option_id",
#     "duorc_ParaphraseRC_build_story_around_qa",
#     "adversarial_qa_dbert_answer_the_following_q",
#     "super_glue_wic_1_0_2",
#     "web_questions_potential_correct_answer",
#     "race_middle_Select_the_best_answer_no_instructions_",
#     "app_reviews_generate_review",
#     "quartz_answer_question_below",
#     "wmt16_translate_ro_en_1_0_0",
#     "wiki_hop_original_choose_best_object_affirmative_1",
#     "super_glue_rte_1_0_2",
#     "gem_common_gen_1_1_0",
#     "wmt14_translate_fr_en_1_0_0",
#     "kilt_tasks_hotpotqa_straighforward_qa",
#     "cot_sensemaking",
#     "app_reviews_convert_to_star_rating",
#     "race_high_Write_a_multi_choice_question_options_given_",
#     "cosmos_qa_1_0_0",
#     "wiki_hop_original_choose_best_object_affirmative_2",
#     "ropes_new_situation_background_answer",
#     "duorc_ParaphraseRC_question_answering",
#     "wiki_qa_Jeopardy_style",
#     "ropes_plain_bottom_hint",
#     "quail_no_prompt_id",
#     "cos_e_v1_11_generate_explanation_given_text",
#     "wiki_bio_guess_person",
#     "winogrande_1_1_0",
#     "adversarial_qa_dbert_question_context_answer",
#     "stream_aqua",
#     "quartz_paragraph_question_plain_concat",
#     "kilt_tasks_hotpotqa_complex_question",
#     "race_middle_Write_a_multi_choice_question_options_given_",
#     "quarel_logic_test",
#     "ropes_prompt_bottom_no_hint",
#     "adversarial_qa_droberta_based_on",
#     "qasc_qa_with_separated_facts_5",
#     "sciq_Multiple_Choice_Closed_Book_",
#     "sciq_Direct_Question_Closed_Book_",
#     "duorc_SelfRC_generate_question_by_answer",
#     "cot_strategyqa_ii",
#     "wiki_hop_original_explain_relation",
#     "cos_e_v1_11_description_question_option_id",
#     "wmt16_translate_fi_en_1_0_0",
#     "fix_punct",
#     "quartz_given_the_fact_answer_the_q",
#     "glue_sst2_2_0_0",
#     "adversarial_qa_droberta_generate_question",
#     "quail_context_question_description_text",
#     "cot_creak",
#     "cnn_dailymail_3_4_0",
#     "wiki_hop_original_generate_subject",
#     "cot_qasc",
#     "ropes_read_background_situation",
#     "huggingface_xsum",
#     "quartz_use_info_from_paragraph_question",
#     "qasc_qa_with_combined_facts_1",
#     "wiki_qa_Direct_Answer_to_Question",
#     "ropes_plain_no_background",
#     "duorc_SelfRC_question_answering",
#     "adversarial_qa_droberta_tell_what_it_is",
#     "gem_e2e_nlg_1_1_0",
#     "race_middle_Read_the_article_and_answer_the_question_no_option_",
#     "gigaword_1_2_0",
#     "quoref_Read_And_Extract_",
#     "duorc_SelfRC_title_generation",
#     "wiki_hop_original_generate_subject_and_object",
#     "dream_generate_first_utterance",
#     "glue_wnli_2_0_0",
#     "wmt16_translate_de_en_1_0_0",
#     "super_glue_copa_1_0_2",
#     "adversarial_qa_droberta_answer_the_following_q",
#     "qasc_qa_with_separated_facts_4",
#     "wiki_bio_what_content",
#     "wiki_qa_found_on_google",
#     "kilt_tasks_hotpotqa_combining_facts",
#     "math_dataset_algebra__linear_1d_1_0_0",
#     "wiki_qa_Generate_Question_from_Topic",
#     "wiki_qa_automatic_system",
#     "race_middle_Select_the_best_answer",
#     "ropes_plain_background_situation",
#     "quarel_choose_between",
#     "duorc_ParaphraseRC_extract_answer",
#     "wiki_qa_Topic_Prediction_Question_Only",
#     "kilt_tasks_hotpotqa_final_exam",
#     "ag_news_subset_1_0_0",
#     "wiki_qa_exercise",
#     "adversarial_qa_dbidaf_based_on",
#     "sciq_Multiple_Choice",
#     "dream_read_the_following_conversation_and_answer_the_question",
#     "wiqa_what_is_the_final_step_of_the_following_process",
#     "wiqa_which_of_the_following_is_the_supposed_perturbation",
#     "quail_context_description_question_text",
#     "cos_e_v1_11_question_option_description_id",
#     "adversarial_qa_dbidaf_question_context_answer",
#     "trivia_qa_rc_1_1_0",
#     "quail_no_prompt_text",
#     "sciq_Direct_Question",
#     "gem_wiki_lingua_english_en_1_1_0",
#     "ropes_prompt_bottom_hint_beginning",
#     "quoref_Answer_Question_Given_Context",
#     "super_glue_wsc_fixed_1_0_2",
#     "wiqa_effect_with_label_answer",
#     "duorc_ParaphraseRC_decide_worth_it",
#     "squad_v2_0_3_0_0",
#     "piqa_1_0_0",
#     "super_glue_record_1_0_2",
#     "quoref_Context_Contains_Answer",
#     "dbpedia_14_given_list_what_category_does_the_paragraph_belong_to",
#     "duorc_SelfRC_build_story_around_qa",
#     "quail_context_question_answer_description_id",
#     "anli_r1_0_1_0",
#     "quarel_heres_a_story",
#     "stream_qed_ii",
#     "race_high_Read_the_article_and_answer_the_question_no_option_",
#     "natural_questions_open_1_0_0",
#     "duorc_ParaphraseRC_movie_director",
#     "quail_description_context_question_answer_text",
#     "quartz_having_read_above_passage",
#     "app_reviews_categorize_rating_using_review",
#     "glue_stsb_2_0_0",
#     "social_i_qa_Show_choices_and_generate_index",
#     "cos_e_v1_11_description_question_option_text",
#     "wiqa_does_the_supposed_perturbation_have_an_effect",
#     "lambada_1_0_0",
#     "hellaswag_1_1_0",
#     "ropes_background_situation_middle",
#     "glue_qnli_2_0_0",
#     "qasc_is_correct_1",
#     "quarel_testing_students",
#     "wiqa_what_is_the_missing_first_step",
#     "para_crawl_enes",
#     "dbpedia_14_pick_one_category_for_the_following_text",
#     "duorc_SelfRC_decide_worth_it",
#     "cot_strategyqa",
#     "wmt16_translate_tr_en_1_0_0",
#     "aeslc_1_0_0",
#     "cos_e_v1_11_rationale",
#     "cos_e_v1_11_i_think",
#     "race_middle_Taking_a_test",
#     "quarel_do_not_use",
#     "race_high_Is_this_the_right_answer",
#     "race_middle_Write_a_multi_choice_question_for_the_following_article",
#     "duorc_SelfRC_generate_question",
#     "multi_news_1_0_0",
#     "race_middle_Is_this_the_right_answer",
#     "imdb_reviews_plain_text_1_0_0",
#     "social_i_qa_Show_choices_and_generate_answer",
#     "quail_context_question_description_answer_id",
#     "cot_creak_ii",
#     "gem_dart_1_1_0",
#     "paws_wiki_1_1_0",
#     "wiqa_what_might_be_the_last_step_of_the_process",
#     "duorc_SelfRC_movie_director",
#     "glue_cola_2_0_0",
#     "bool_q_1_0_0",
#     "drop_2_0_0",
#     "cot_esnli_ii",
#     "race_high_Select_the_best_answer",
#     "cos_e_v1_11_question_option_description_text",
#     "social_i_qa_Generate_the_question_from_the_answer",
#     "wiki_bio_comprehension",
#     "race_high_Select_the_best_answer_no_instructions_",
#     "anli_r3_0_1_0",
#     "wiki_bio_who",
#     "web_questions_short_general_knowledge_q",
#     "qasc_qa_with_separated_facts_3",
#     "cos_e_v1_11_explain_why_human",
#     "qasc_qa_with_separated_facts_2",
#     "race_high_Taking_a_test",
#     "qasc_is_correct_2",
#     "wiki_hop_original_generate_object",
#     "wiki_qa_Topic_Prediction_Answer_Only",
#     "glue_mnli_2_0_0",
#     "wiki_bio_key_content",
#     "quoref_Guess_Title_For_Context",
#     "definite_pronoun_resolution_1_1_0",
#     "ropes_given_background_situation",
#     "qasc_qa_with_separated_facts_1",
#     "quoref_Found_Context_Online",
#     "stream_aqua_ii",
#     "cot_sensemaking_ii",
#     "adversarial_qa_droberta_question_context_answer",
#     "race_high_Select_the_best_answer_generate_span_",
#     "ai2_arc_ARC_Easy_1_0_0",
#     "adversarial_qa_dbert_tell_what_it_is",
#     "cot_gsm8k",
#     "quail_context_description_question_answer_text",
#     "trec_1_0_0",
#     "quartz_answer_question_based_on",
#     "super_glue_multirc_1_0_2",
#     "dream_generate_last_utterance",
#     "sciq_Multiple_Choice_Question_First",
#     "cot_esnli",
#     "race_middle_Select_the_best_answer_generate_span_",
#     "social_i_qa_I_was_wondering",
#     "quoref_Given_Context_Answer_Question",
#     "duorc_SelfRC_extract_answer",
#     "quail_description_context_question_text",
#     "race_high_Write_a_multi_choice_question_for_the_following_article",
# ]

FLAN_TASKS = [
    "ropes_new_situation_background_answer",
    "bool_q_1_0_0",
    "app_reviews_generate_review",
    "quail_description_context_question_answer_id",
    "app_reviews_convert_to_star_rating",
    "wiki_bio_who",
    "quail_context_description_question_answer_text",
    "quarel_heres_a_story",
    "math_dataset_algebra__linear_1d_1_0_0",
    "cos_e_v1_11_question_description_option_text",
    "cos_e_v1_11_explain_why_human",
    "yelp_polarity_reviews_0_2_0",
    "trivia_qa_rc_1_1_0",
    "wiki_qa_Direct_Answer_to_Question",
    "wiqa_what_might_be_the_last_step_of_the_process",
    "quarel_choose_between",
    "sciq_Multiple_Choice_Closed_Book_",
    "wiqa_effect_with_string_answer",
    "super_glue_multirc_1_0_2",
    "ropes_plain_no_background",
    "glue_stsb_2_0_0",
    "wiki_qa_Jeopardy_style",
    "glue_sst2_2_0_0",
    "wmt16_translate_fi_en_1_0_0",
    "anli_r1_0_1_0",
    "ai2_arc_ARC_Challenge_1_0_0",
    "wiki_bio_guess_person",
    "social_i_qa_Generate_the_question_from_the_answer",
    "race_high_Write_a_multi_choice_question_options_given_",
    "adversarial_qa_dbert_generate_question",
    "wiki_qa_Decide_good_answer",
    "glue_cola_2_0_0",
    "ag_news_subset_1_0_0",
    "duorc_ParaphraseRC_movie_director",
    "web_questions_potential_correct_answer",
    "glue_qqp_2_0_0",
    "quartz_answer_question_below",
    "wiqa_which_of_the_following_is_the_supposed_perturbation",
    "quartz_use_info_from_paragraph_question",
    "wiki_hop_original_generate_object",
    "social_i_qa_Show_choices_and_generate_answer",
    "race_middle_Select_the_best_answer_generate_span_",
    "kilt_tasks_hotpotqa_combining_facts",
    "qasc_qa_with_separated_facts_4",
    "super_glue_rte_1_0_2",
    "wiqa_effect_with_label_answer",
    "adversarial_qa_dbidaf_tell_what_it_is",
    "quail_description_context_question_text",
    "race_high_Read_the_article_and_answer_the_question_no_option_",
    "fix_punct",
    "ropes_background_new_situation_answer",
    "sciq_Multiple_Choice_Question_First",
    "adversarial_qa_dbert_question_context_answer",
    "adversarial_qa_dbidaf_question_context_answer",
    "app_reviews_convert_to_rating",
    "kilt_tasks_hotpotqa_straighforward_qa",
    "wiki_hop_original_choose_best_object_affirmative_2",
    "duorc_ParaphraseRC_extract_answer",
    "wmt16_translate_tr_en_1_0_0",
    "race_middle_Write_a_multi_choice_question_options_given_",
    "sciq_Direct_Question",
    "dbpedia_14_given_a_choice_of_categories_",
    "wiki_hop_original_generate_subject",
    "paws_wiki_1_1_0",
    "duorc_SelfRC_decide_worth_it",
    "wiqa_does_the_supposed_perturbation_have_an_effect",
    "duorc_SelfRC_question_answering",
    "trec_1_0_0",
    "word_segment",
    "ropes_read_background_situation",
    "adversarial_qa_droberta_tell_what_it_is",
    "qasc_is_correct_1",
    "adversarial_qa_dbert_tell_what_it_is",
    "race_middle_Select_the_best_answer",
    "qasc_qa_with_separated_facts_3",
    "super_glue_copa_1_0_2",
    "race_middle_Read_the_article_and_answer_the_question_no_option_",
    "qasc_qa_with_separated_facts_2",
    "duorc_ParaphraseRC_answer_question",
    "imdb_reviews_plain_text_1_0_0",
    "true_case",
    "quarel_logic_test",
    "quoref_Found_Context_Online",
    "wiki_bio_key_content",
    "glue_mnli_2_0_0",
    "cos_e_v1_11_i_think",
    "cos_e_v1_11_rationale",
    "dream_read_the_following_conversation_and_answer_the_question",
    "dream_answer_to_dialogue",
    "sciq_Multiple_Choice",
    "race_middle_Write_a_multi_choice_question_for_the_following_article",
    "wiki_qa_Topic_Prediction_Answer_Only",
    "ropes_prompt_mix",
    "quoref_Read_And_Extract_",
    "qasc_qa_with_separated_facts_5",
    "quoref_What_Is_The_Answer",
    "wiqa_what_might_be_the_first_step_of_the_process",
    "quail_no_prompt_text",
    "wiki_bio_comprehension",
    "adversarial_qa_droberta_based_on",
    "quoref_Guess_Answer",
    "race_high_Select_the_best_answer_generate_span_",
    "adversarial_qa_droberta_generate_question",
    "quartz_given_the_fact_answer_the_q",
    "wiqa_what_is_the_missing_first_step",
    "cnn_dailymail_3_4_0",
    "wiki_hop_original_choose_best_object_affirmative_3",
    "huggingface_xsum",
    "wmt14_translate_fr_en_1_0_0",
    "lambada_1_0_0",
    "quoref_Given_Context_Answer_Question",
    "race_high_Select_the_best_answer",
    "quarel_do_not_use",
    "natural_questions_open_1_0_0",
    "super_glue_record_1_0_2",
    "qasc_qa_with_separated_facts_1",
    "wiki_qa_automatic_system",
    "duorc_SelfRC_answer_question",
    "wiki_hop_original_choose_best_object_interrogative_1",
    "aeslc_1_0_0",
    "wiki_qa_Topic_Prediction_Question_Only",
    "adversarial_qa_dbert_based_on",
    "dbpedia_14_given_list_what_category_does_the_paragraph_belong_to",
    "ropes_prompt_beginning",
    "adversarial_qa_dbidaf_answer_the_following_q",
    "openbookqa_0_1_0",
    "anli_r3_0_1_0",
    "quoref_Answer_Test",
    "dream_baseline",
    "ropes_plain_background_situation",
    "adversarial_qa_droberta_answer_the_following_q",
    "anli_r2_0_1_0",
    "wiki_qa_Generate_Question_from_Topic",
    "quoref_Answer_Question_Given_Context",
    "quoref_Context_Contains_Answer",
    "quail_description_context_question_answer_text",
    "quoref_Answer_Friend_Question",
    "cos_e_v1_11_description_question_option_id",
    "wiki_hop_original_choose_best_object_interrogative_2",
    "race_middle_Is_this_the_right_answer",
    "quail_context_question_description_text",
    "glue_wnli_2_0_0",
    "qasc_is_correct_2",
    "sciq_Direct_Question_Closed_Book_",
    "gem_web_nlg_en_1_1_0",
    "ai2_arc_ARC_Easy_1_0_0",
    "adversarial_qa_dbert_answer_the_following_q",
    "duorc_ParaphraseRC_decide_worth_it",
    "unified_qa_science_inst",
    "quail_context_question_description_answer_id",
    "quartz_use_info_from_question_paragraph",
    "wmt16_translate_ro_en_1_0_0",
    "ropes_background_situation_middle",
    "duorc_ParaphraseRC_question_answering",
    "kilt_tasks_hotpotqa_final_exam",
    "web_questions_get_the_answer",
    "wiki_bio_what_content",
    "glue_qnli_2_0_0",
    "adversarial_qa_droberta_question_context_answer",
    "social_i_qa_Show_choices_and_generate_index",
    "race_middle_Taking_a_test",
    "web_questions_whats_the_answer",
    "dbpedia_14_pick_one_category_for_the_following_text",
    "ropes_plain_bottom_hint",
    "web_questions_short_general_knowledge_q",
    "adversarial_qa_dbidaf_based_on",
    "social_i_qa_Generate_answer",
    "quarel_testing_students",
    "snli_1_1_0",
    "quail_context_question_description_answer_text",
    "quoref_Guess_Title_For_Context",
    "duorc_ParaphraseRC_build_story_around_qa",
    "wmt16_translate_de_en_1_0_0",
    "qasc_qa_with_combined_facts_1",
    "drop_2_0_0",
    "quoref_Find_Answer",
    "dream_generate_first_utterance",
    "cos_e_v1_11_question_option_description_text",
    "quail_context_question_answer_description_id",
    "duorc_ParaphraseRC_title_generation",
    "cos_e_v1_11_generate_explanation_given_text",
    "hellaswag_1_1_0",
    "glue_mrpc_2_0_0",
    "winogrande_1_1_0",
    "kilt_tasks_hotpotqa_complex_question",
    "app_reviews_categorize_rating_using_review",
    "coqa_1_0_0",
    "duorc_SelfRC_movie_director",
    "super_glue_wsc_fixed_1_0_2",
    "duorc_SelfRC_generate_question_by_answer",
    "quartz_paragraph_question_plain_concat",
    "wiqa_what_is_the_final_step_of_the_following_process",
    "race_high_Is_this_the_right_answer",
    "gem_common_gen_1_1_0",
    "duorc_SelfRC_extract_answer",
    "wiki_qa_found_on_google",
    "wiki_qa_Is_This_True_",
    "squad_v2_0_3_0_0",
    "cos_e_v1_11_aligned_with_common_sense",
    "wiki_hop_original_choose_best_object_affirmative_1",
    "wiki_hop_original_generate_subject_and_object",
    "social_i_qa_I_was_wondering",
    "gem_e2e_nlg_1_1_0",
    "super_glue_cb_1_0_2",
    "squad_v1_1_3_0_0",
    "quail_context_description_question_answer_id",
    "quail_no_prompt_id",
    "cos_e_v1_11_question_description_option_id",
    "quail_context_description_question_text",
    "kilt_tasks_hotpotqa_formulate",
    "gem_wiki_lingua_english_en_1_1_0",
    "multi_news_1_0_0",
    "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
    "ropes_given_background_situation",
    "wiki_qa_exercise",
    "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
    "cosmos_qa_1_0_0",
    "dream_generate_last_utterance",
    "duorc_SelfRC_title_generation",
    "ropes_prompt_bottom_no_hint",
    "quail_context_question_answer_description_text",
    "gigaword_1_2_0",
    "cos_e_v1_11_question_option_description_id",
    "piqa_1_0_0",
    "quac_1_0_0",
    "quartz_read_passage_below_choose",
    "race_high_Taking_a_test",
    "cos_e_v1_11_description_question_option_text",
    "para_crawl_enes",
    "web_questions_question_answer",
    "super_glue_wic_1_0_2",
    "race_high_Write_a_multi_choice_question_for_the_following_article",
    "quartz_answer_question_based_on",
    "ropes_prompt_bottom_hint_beginning",
    "duorc_ParaphraseRC_generate_question_by_answer",
    "duorc_SelfRC_generate_question",
    "wiki_hop_original_explain_relation",
    "adversarial_qa_dbidaf_generate_question",
    "race_high_Select_the_best_answer_no_instructions_",
    "wiki_qa_Topic_Prediction_Question_and_Answer_Pair",
    "duorc_SelfRC_build_story_around_qa",
    "race_middle_Select_the_best_answer_no_instructions_",
    "gem_dart_1_1_0",
    "definite_pronoun_resolution_1_1_0",
    "quartz_having_read_above_passage",
    "duorc_ParaphraseRC_generate_question",
]

ZHAN_SUBSET = [
    "niv2_question_generation",
    "niv2_question_answering",
    "niv2_wrong_candidate_generation",
    "ultrachat_31",
    "ultrachat_15",
    "ultrachat_19",
    "MATH/PRM-800K",
    "ARB",
    "scienceqa",
    "huggingface_xsum",
    "fix_punct",
    "unified_qa_science_inst",
]

ADAUNI_INTERFERENCE_31 = [
    "wiki_hop_original_choose_best_object_affirmative_1",
    "wiki_hop_original_choose_best_object_affirmative_2",
    "anatomy",
    "professional_medicine",
    "cot_strategyqa",
    "airoboros",
    "quac_1_0_0",
    "high_school_government_and_politics",
    "math_dataset_algebra__linear_1d_1_0_0",
    "niv2_grammar_error_detection",
    "niv2_sentence_composition",
    "wiki_bio_guess_person",
    "web_questions_whats_the_answer",
    "ropes_background_situation_middle",
    "sciq_Direct_Question",
    "ropes_new_situation_background_answer",
    "human_aging",
    "cot_ecqa_ii",
    "cot_esnli",
    "niv2_discourse_connective_identification",
    "sociology",
    "niv2_code_to_text",
    "coqa_1_0_0",
    "super_glue_wic_1_0_2",
    "college_medicine",
    "ropes_prompt_bottom_no_hint",
    "fix_punct",
    "niv2_ethics_classification",
    "guanaco",
    "wiqa_what_might_be_the_first_step_of_the_process",
    "ultrachat_19",
]

# similar sequences: discovered through cos similarity of phi2 (fc[12])
similar10 = [
    "ropes_background_new_situation_answer",
    "wiki_hop_original_generate_object",
    "ropes_new_situation_background_answer",
    "ropes_prompt_beginning",
    "ropes_read_background_situation",
    "ropes_plain_bottom_hint",
    "quarel_heres_a_story",
    "wiki_hop_original_generate_subject",
    "social_i_qa_Generate_the_question_from_the_answer",
    "ropes_background_situation_middle",
]

# most dissimilar sequences: discovered through cos similarity of phi2 (fc[12])
distinct10 = [
    "wiqa_what_is_the_final_step_of_the_following_process",
    "duorc_SelfRC_generate_question_by_answer",
    "super_glue_cb_1_0_2",
    "sciq_Multiple_Choice",
    "ultrachat_25",
    "niv2_explanation",
    "aeslc_1_0_0",
    "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
    "high_school_psychology",
    "niv2_dialogue_act_recognition",
]


# FLAN CLUSTERS: obtained through k-means clustering of sordonia/library-phi_2-v3
c8 = [
    "glue_sst2_2_0_0",
    "adversarial_qa_droberta_generate_question",
    "stream_qed",
    "super_glue_record_1_0_2",
    "yelp_polarity_reviews_0_2_0",
    "lambada_1_0_0",
    "dream_generate_last_utterance",
    "ag_news_subset_1_0_0",
    "duorc_ParaphraseRC_title_generation",
    "adversarial_qa_dbidaf_generate_question",
    "quoref_Guess_Title_For_Context",
    "fix_punct",
    "imdb_reviews_plain_text_1_0_0",
    "race_middle_Write_a_multi_choice_question_for_the_following_article",
    "duorc_SelfRC_title_generation",
    "anli_r2_0_1_0",
    "race_high_Write_a_multi_choice_question_for_the_following_article",
    "anli_r1_0_1_0",
    "cot_ecqa",
    "race_high_Write_a_multi_choice_question_options_given_",
    "adversarial_qa_dbert_generate_question",
    "race_middle_Write_a_multi_choice_question_options_given_",
]
c3 = [
    "dream_read_the_following_conversation_and_answer_the_question",
    "cos_e_v1_11_question_option_description_text",
    "social_i_qa_Show_choices_and_generate_answer",
    "sciq_Direct_Question_Closed_Book_",
    "qasc_qa_with_separated_facts_3",
    "sciq_Multiple_Choice",
    "cos_e_v1_11_question_description_option_text",
    "sciq_Direct_Question",
    "qasc_qa_with_separated_facts_2",
    "wiqa_which_of_the_following_is_the_supposed_perturbation",
    "cos_e_v1_11_question_option_description_id",
    "cot_ecqa_ii",
    "wiqa_effect_with_string_answer",
    "quarel_do_not_use",
    "qasc_qa_with_separated_facts_5",
    "dream_baseline",
    "quartz_having_read_above_passage",
    "cos_e_v1_11_question_description_option_id",
    "qasc_qa_with_separated_facts_1",
    "quarel_heres_a_story",
    "qasc_qa_with_combined_facts_1",
    "cos_e_v1_11_description_question_option_id",
    "quarel_choose_between",
    "social_i_qa_Show_choices_and_generate_index",
    "sciq_Multiple_Choice_Closed_Book_",
    "quartz_use_info_from_paragraph_question",
    "quarel_testing_students",
    "qasc_qa_with_separated_facts_4",
    "quartz_read_passage_below_choose",
    "wiqa_effect_with_label_answer",
    "quarel_logic_test",
    "sciq_Multiple_Choice_Question_First",
]
c4 = [
    "race_middle_Read_the_article_and_answer_the_question_no_option_",
    "race_high_Select_the_best_answer",
    "quail_description_context_question_answer_id",
    "quail_context_question_description_text",
    "race_high_Read_the_article_and_answer_the_question_no_option_",
    "race_high_Select_the_best_answer_no_instructions_",
    "quail_context_description_question_answer_id",
    "race_high_Taking_a_test",
    "race_middle_Select_the_best_answer",
    "quail_context_question_description_answer_id",
    "quail_description_context_question_answer_text",
    "quail_context_question_answer_description_text",
    "race_high_Select_the_best_answer_generate_span_",
    "race_middle_Select_the_best_answer_generate_span_",
    "quail_context_question_answer_description_id",
    "quail_context_description_question_answer_text",
    "quail_context_description_question_text",
    "quail_context_question_description_answer_text",
    "quail_description_context_question_text",
    "race_middle_Taking_a_test",
    "quail_no_prompt_id",
    "quail_no_prompt_text",
    "race_middle_Select_the_best_answer_no_instructions_",
]
c0 = [
    "adversarial_qa_dbidaf_question_context_answer",
    "true_case",
    "cot_sensemaking",
    "trec_1_0_0",
    "quartz_answer_question_based_on",
    "cos_e_v1_11_rationale",
    "natural_questions_open_1_0_0",
    "web_questions_whats_the_answer",
    "anli_r3_0_1_0",
    "kilt_tasks_hotpotqa_final_exam",
    "glue_cola_2_0_0",
    "cos_e_v1_11_generate_explanation_given_text",
    "adversarial_qa_droberta_tell_what_it_is",
    "cot_creak",
    "cot_gsm8k_ii",
    "math_dataset_algebra__linear_1d_1_0_0",
    "quartz_use_info_from_question_paragraph",
    "web_questions_question_answer",
    "dbpedia_14_pick_one_category_for_the_following_text",
    "dbpedia_14_given_a_choice_of_categories_",
    "kilt_tasks_hotpotqa_combining_facts",
    "web_questions_short_general_knowledge_q",
    "kilt_tasks_hotpotqa_straighforward_qa",
    "cos_e_v1_11_i_think",
    "dbpedia_14_given_list_what_category_does_the_paragraph_belong_to",
    "adversarial_qa_droberta_based_on",
    "web_questions_get_the_answer",
    "adversarial_qa_dbert_answer_the_following_q",
    "kilt_tasks_hotpotqa_complex_question",
    "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
    "adversarial_qa_droberta_question_context_answer",
    "cos_e_v1_11_explain_why_human",
    "cot_creak_ii",
    "cos_e_v1_11_description_question_option_text",
    "web_questions_potential_correct_answer",
    "trivia_qa_rc_1_1_0",
    "stream_qed_ii",
    "wiki_bio_guess_person",
    "cos_e_v1_11_aligned_with_common_sense",
    "adversarial_qa_dbidaf_answer_the_following_q",
    "adversarial_qa_droberta_answer_the_following_q",
    "cot_sensemaking_ii",
    "adversarial_qa_dbert_tell_what_it_is",
    "kilt_tasks_hotpotqa_formulate",
    "social_i_qa_I_was_wondering",
    "cosmos_qa_1_0_0",
    "adversarial_qa_dbert_based_on",
    "adversarial_qa_dbidaf_based_on",
    "drop_2_0_0",
    "adversarial_qa_dbert_question_context_answer",
    "adversarial_qa_dbidaf_tell_what_it_is",
    "social_i_qa_Generate_answer",
    "squad_v1_1_3_0_0",
]
c5 = [
    "app_reviews_convert_to_star_rating",
    "super_glue_rte_1_0_2",
    "wiki_qa_found_on_google",
    "app_reviews_categorize_rating_using_review",
    "super_glue_wic_1_0_2",
    "race_middle_Is_this_the_right_answer",
    "super_glue_cb_1_0_2",
    "wiki_qa_Topic_Prediction_Answer_Only",
    "paws_wiki_1_1_0",
    "wiki_qa_Direct_Answer_to_Question",
    "super_glue_wsc_fixed_1_0_2",
    "wiqa_does_the_supposed_perturbation_have_an_effect",
    "wiki_qa_Is_This_True_",
    "unified_qa_science_inst",
    "super_glue_multirc_1_0_2",
    "snli_1_1_0",
    "app_reviews_convert_to_rating",
    "race_high_Is_this_the_right_answer",
    "cot_strategyqa",
    "glue_qqp_2_0_0",
    "wiki_qa_exercise",
    "wiki_qa_automatic_system",
    "qasc_is_correct_1",
    "squad_v2_0_3_0_0",
    "wiki_qa_Topic_Prediction_Question_Only",
    "glue_stsb_2_0_0",
    "glue_qnli_2_0_0",
    "glue_mnli_2_0_0",
    "super_glue_copa_1_0_2",
    "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
    "social_i_qa_Generate_the_question_from_the_answer",
    "qasc_is_correct_2",
    "wiki_qa_Topic_Prediction_Question_and_Answer_Pair",
    "wiki_qa_Decide_good_answer",
    "wiki_qa_Jeopardy_style",
    "wiki_qa_Generate_Question_from_Topic",
    "definite_pronoun_resolution_1_1_0",
    "glue_wnli_2_0_0",
    "glue_mrpc_2_0_0",
    "cot_qasc",
    "cot_strategyqa_ii",
    "stream_aqua_ii",
]
c1 = [
    "wiqa_what_might_be_the_first_step_of_the_process",
    "huggingface_xsum",
    "cot_esnli",
    "cot_gsm8k",
    "gem_dart_1_1_0",
    "gem_common_gen_1_1_0",
    "stream_aqua",
    "cnn_dailymail_3_4_0",
    "gem_wiki_lingua_english_en_1_1_0",
    "gigaword_1_2_0",
    "gem_web_nlg_en_1_1_0",
    "word_segment",
    "app_reviews_generate_review",
    "wmt16_translate_de_en_1_0_0",
    "aeslc_1_0_0",
    "dream_generate_first_utterance",
    "wmt16_translate_fi_en_1_0_0",
    "dream_answer_to_dialogue",
    "gem_e2e_nlg_1_1_0",
    "para_crawl_enes",
    "wmt14_translate_fr_en_1_0_0",
    "cot_esnli_ii",
    "wiqa_what_is_the_missing_first_step",
    "coqa_1_0_0",
]
c7 = [
    "wiqa_what_is_the_final_step_of_the_following_process",
    "wmt16_translate_ro_en_1_0_0",
    "wiqa_what_might_be_the_last_step_of_the_process",
    "wiki_bio_key_content",
    "duorc_SelfRC_build_story_around_qa",
    "wiki_bio_what_content",
    "wiki_bio_who",
    "wmt16_translate_tr_en_1_0_0",
    "wiki_bio_comprehension",
    "duorc_ParaphraseRC_build_story_around_qa",
    "multi_news_1_0_0",
]
c9 = [
    "ropes_background_new_situation_answer",
    "ropes_prompt_bottom_no_hint",
    "ropes_plain_background_situation",
    "quartz_given_the_fact_answer_the_q",
    "quartz_answer_question_below",
    "ropes_new_situation_background_answer",
    "ropes_given_background_situation",
    "ropes_prompt_bottom_hint_beginning",
    "ropes_prompt_beginning",
    "ropes_read_background_situation",
    "ropes_plain_bottom_hint",
    "ropes_plain_no_background",
    "quartz_paragraph_question_plain_concat",
    "ropes_prompt_mix",
    "ropes_background_situation_middle",
]
c2 = [
    "quoref_Context_Contains_Answer",
    "duorc_SelfRC_generate_question_by_answer",
    "quoref_Find_Answer",
    "duorc_ParaphraseRC_movie_director",
    "duorc_ParaphraseRC_answer_question",
    "quoref_Found_Context_Online",
    "quoref_Read_And_Extract_",
    "duorc_ParaphraseRC_decide_worth_it",
    "quoref_What_Is_The_Answer",
    "duorc_ParaphraseRC_generate_question",
    "quac_1_0_0",
    "quoref_Answer_Test",
    "duorc_SelfRC_question_answering",
    "duorc_ParaphraseRC_generate_question_by_answer",
    "duorc_ParaphraseRC_extract_answer",
    "duorc_SelfRC_answer_question",
    "duorc_SelfRC_decide_worth_it",
    "duorc_ParaphraseRC_question_answering",
    "quoref_Answer_Question_Given_Context",
    "duorc_SelfRC_extract_answer",
    "quoref_Guess_Answer",
    "quoref_Answer_Friend_Question",
    "duorc_SelfRC_movie_director",
    "duorc_SelfRC_generate_question",
    "quoref_Given_Context_Answer_Question",
]
c6 = [
    "wiki_hop_original_generate_object",
    "wiki_hop_original_choose_best_object_affirmative_3",
    "wiki_hop_original_choose_best_object_interrogative_1",
    "wiki_hop_original_explain_relation",
    "wiki_hop_original_choose_best_object_affirmative_1",
    "wiki_hop_original_choose_best_object_interrogative_2",
    "wiki_hop_original_generate_subject",
    "wiki_hop_original_choose_best_object_affirmative_2",
    "wiki_hop_original_generate_subject_and_object",
]


# FLAN CLUSTERS: obtained through k-means clustering of sordonia/library-phi_2-v3-2epc
c1_2e = [
    "glue_sst2_2_0_0",
    "adversarial_qa_droberta_generate_question",
    "true_case",
    "stream_qed",
    "huggingface_xsum",
    "cot_esnli",
    "cot_gsm8k",
    "trec_1_0_0",
    "yelp_polarity_reviews_0_2_0",
    "lambada_1_0_0",
    "glue_cola_2_0_0",
    "ag_news_subset_1_0_0",
    "gem_dart_1_1_0",
    "math_dataset_algebra__linear_1d_1_0_0",
    "cnn_dailymail_3_4_0",
    "wiki_hop_original_explain_relation",
    "dbpedia_14_given_list_what_category_does_the_paragraph_belong_to",
    "gem_wiki_lingua_english_en_1_1_0",
    "fix_punct",
    "imdb_reviews_plain_text_1_0_0",
    "race_middle_Write_a_multi_choice_question_for_the_following_article",
    "gigaword_1_2_0",
    "dbpedia_14_given_a_list_of_category_what_does_the_title_belong_to",
    "gem_web_nlg_en_1_1_0",
    "word_segment",
    "race_high_Write_a_multi_choice_question_for_the_following_article",
    "wmt16_translate_de_en_1_0_0",
    "cot_ecqa",
    "aeslc_1_0_0",
    "dream_generate_first_utterance",
    "wmt16_translate_fi_en_1_0_0",
    "dream_answer_to_dialogue",
    "para_crawl_enes",
    "adversarial_qa_dbert_generate_question",
    "race_middle_Write_a_multi_choice_question_options_given_",
    "wmt14_translate_fr_en_1_0_0",
]
c7_2e = [
    "dream_read_the_following_conversation_and_answer_the_question",
    "app_reviews_convert_to_star_rating",
    "cos_e_v1_11_question_option_description_text",
    "social_i_qa_Show_choices_and_generate_answer",
    "quartz_answer_question_based_on",
    "sciq_Direct_Question_Closed_Book_",
    "qasc_qa_with_separated_facts_3",
    "quartz_given_the_fact_answer_the_q",
    "quartz_answer_question_below",
    "kilt_tasks_hotpotqa_final_exam",
    "sciq_Multiple_Choice",
    "wiqa_does_the_supposed_perturbation_have_an_effect",
    "cos_e_v1_11_question_description_option_text",
    "wiki_qa_Is_This_True_",
    "quartz_use_info_from_question_paragraph",
    "sciq_Direct_Question",
    "qasc_qa_with_separated_facts_2",
    "wiqa_which_of_the_following_is_the_supposed_perturbation",
    "app_reviews_convert_to_rating",
    "cos_e_v1_11_question_option_description_id",
    "wiqa_effect_with_string_answer",
    "qasc_qa_with_separated_facts_5",
    "dream_baseline",
    "quartz_having_read_above_passage",
    "cos_e_v1_11_question_description_option_id",
    "qasc_qa_with_separated_facts_1",
    "cos_e_v1_11_description_question_option_text",
    "qasc_qa_with_combined_facts_1",
    "qasc_is_correct_1",
    "cos_e_v1_11_description_question_option_id",
    "social_i_qa_Check_if_a_random_answer_is_valid_or_not",
    "sciq_Multiple_Choice_Closed_Book_",
    "quartz_use_info_from_paragraph_question",
    "qasc_is_correct_2",
    "qasc_qa_with_separated_facts_4",
    "quartz_read_passage_below_choose",
    "quartz_paragraph_question_plain_concat",
    "sciq_Multiple_Choice_Question_First",
]
c8_2e = [
    "race_middle_Read_the_article_and_answer_the_question_no_option_",
    "race_high_Select_the_best_answer",
    "quail_description_context_question_answer_id",
    "quail_context_question_description_text",
    "race_high_Read_the_article_and_answer_the_question_no_option_",
    "race_high_Select_the_best_answer_no_instructions_",
    "quail_context_description_question_answer_id",
    "race_high_Taking_a_test",
    "super_glue_multirc_1_0_2",
    "race_middle_Select_the_best_answer",
    "quail_context_question_description_answer_id",
    "quail_description_context_question_answer_text",
    "quail_context_question_answer_description_text",
    "race_high_Select_the_best_answer_generate_span_",
    "race_middle_Select_the_best_answer_generate_span_",
    "quail_context_question_answer_description_id",
    "quail_context_description_question_answer_text",
    "quail_context_description_question_text",
    "quail_context_question_description_answer_text",
    "quail_description_context_question_text",
    "race_middle_Taking_a_test",
    "quail_no_prompt_id",
    "quail_no_prompt_text",
    "race_middle_Select_the_best_answer_no_instructions_",
]
c2_2e = [
    "adversarial_qa_dbidaf_question_context_answer",
    "super_glue_record_1_0_2",
    "wiki_hop_original_generate_object",
    "adversarial_qa_droberta_tell_what_it_is",
    "dbpedia_14_given_a_choice_of_categories_",
    "wiki_hop_original_choose_best_object_affirmative_3",
    "quac_1_0_0",
    "wiki_hop_original_choose_best_object_interrogative_1",
    "wiki_hop_original_choose_best_object_affirmative_1",
    "adversarial_qa_dbert_answer_the_following_q",
    "wiki_hop_original_choose_best_object_interrogative_2",
    "adversarial_qa_droberta_question_context_answer",
    "squad_v2_0_3_0_0",
    "wiki_hop_original_generate_subject",
    "wiki_bio_guess_person",
    "adversarial_qa_dbidaf_answer_the_following_q",
    "adversarial_qa_droberta_answer_the_following_q",
    "adversarial_qa_dbert_tell_what_it_is",
    "race_high_Write_a_multi_choice_question_options_given_",
    "wiki_hop_original_choose_best_object_affirmative_2",
    "wiki_hop_original_generate_subject_and_object",
    "drop_2_0_0",
    "adversarial_qa_dbert_question_context_answer",
    "adversarial_qa_dbidaf_tell_what_it_is",
]
c6_2e = [
    "super_glue_rte_1_0_2",
    "cot_sensemaking",
    "super_glue_wic_1_0_2",
    "cos_e_v1_11_rationale",
    "anli_r3_0_1_0",
    "dream_generate_last_utterance",
    "paws_wiki_1_1_0",
    "cos_e_v1_11_generate_explanation_given_text",
    "cot_creak",
    "stream_aqua",
    "snli_1_1_0",
    "cos_e_v1_11_i_think",
    "glue_qqp_2_0_0",
    "cos_e_v1_11_explain_why_human",
    "anli_r2_0_1_0",
    "anli_r1_0_1_0",
    "glue_stsb_2_0_0",
    "cos_e_v1_11_aligned_with_common_sense",
    "glue_mnli_2_0_0",
    "social_i_qa_I_was_wondering",
    "cosmos_qa_1_0_0",
    "glue_mrpc_2_0_0",
    "social_i_qa_Generate_answer",
]
c3_2e = [
    "wiqa_what_might_be_the_first_step_of_the_process",
    "wiqa_what_is_the_final_step_of_the_following_process",
    "wmt16_translate_ro_en_1_0_0",
    "wiqa_what_might_be_the_last_step_of_the_process",
    "wiki_bio_key_content",
    "gem_common_gen_1_1_0",
    "duorc_SelfRC_build_story_around_qa",
    "app_reviews_generate_review",
    "wiki_bio_what_content",
    "wiki_bio_who",
    "gem_e2e_nlg_1_1_0",
    "cot_esnli_ii",
    "wmt16_translate_tr_en_1_0_0",
    "wiqa_what_is_the_missing_first_step",
    "wiki_bio_comprehension",
    "coqa_1_0_0",
    "duorc_ParaphraseRC_build_story_around_qa",
    "multi_news_1_0_0",
]
c0_2e = [
    "ropes_background_new_situation_answer",
    "ropes_prompt_bottom_no_hint",
    "ropes_plain_background_situation",
    "ropes_new_situation_background_answer",
    "ropes_given_background_situation",
    "ropes_prompt_bottom_hint_beginning",
    "ropes_prompt_beginning",
    "ropes_read_background_situation",
    "ropes_plain_bottom_hint",
    "ropes_plain_no_background",
    "ropes_prompt_mix",
    "ropes_background_situation_middle",
]
c4_2e = [
    "wiki_qa_found_on_google",
    "app_reviews_categorize_rating_using_review",
    "race_middle_Is_this_the_right_answer",
    "super_glue_cb_1_0_2",
    "wiki_qa_Topic_Prediction_Answer_Only",
    "wiki_qa_Direct_Answer_to_Question",
    "super_glue_wsc_fixed_1_0_2",
    "cot_gsm8k_ii",
    "unified_qa_science_inst",
    "race_high_Is_this_the_right_answer",
    "cot_strategyqa",
    "cot_ecqa_ii",
    "quarel_do_not_use",
    "wiki_qa_exercise",
    "wiki_qa_automatic_system",
    "cot_creak_ii",
    "quarel_heres_a_story",
    "quarel_choose_between",
    "stream_qed_ii",
    "wiki_qa_Topic_Prediction_Question_Only",
    "glue_qnli_2_0_0",
    "cot_sensemaking_ii",
    "super_glue_copa_1_0_2",
    "social_i_qa_Generate_the_question_from_the_answer",
    "social_i_qa_Show_choices_and_generate_index",
    "quarel_testing_students",
    "wiki_qa_Topic_Prediction_Question_and_Answer_Pair",
    "wiki_qa_Decide_good_answer",
    "wiki_qa_Jeopardy_style",
    "wiki_qa_Generate_Question_from_Topic",
    "definite_pronoun_resolution_1_1_0",
    "wiqa_effect_with_label_answer",
    "glue_wnli_2_0_0",
    "cot_qasc",
    "cot_strategyqa_ii",
    "quarel_logic_test",
    "stream_aqua_ii",
]
c5_2e = [
    "quoref_Context_Contains_Answer",
    "duorc_SelfRC_generate_question_by_answer",
    "quoref_Find_Answer",
    "duorc_ParaphraseRC_movie_director",
    "duorc_ParaphraseRC_answer_question",
    "quoref_Found_Context_Online",
    "quoref_Read_And_Extract_",
    "duorc_ParaphraseRC_title_generation",
    "duorc_ParaphraseRC_decide_worth_it",
    "quoref_What_Is_The_Answer",
    "duorc_ParaphraseRC_generate_question",
    "quoref_Guess_Title_For_Context",
    "quoref_Answer_Test",
    "duorc_SelfRC_question_answering",
    "duorc_SelfRC_title_generation",
    "duorc_ParaphraseRC_generate_question_by_answer",
    "duorc_ParaphraseRC_extract_answer",
    "duorc_SelfRC_answer_question",
    "duorc_SelfRC_decide_worth_it",
    "duorc_ParaphraseRC_question_answering",
    "quoref_Answer_Question_Given_Context",
    "duorc_SelfRC_extract_answer",
    "quoref_Guess_Answer",
    "quoref_Answer_Friend_Question",
    "duorc_SelfRC_movie_director",
    "duorc_SelfRC_generate_question",
    "quoref_Given_Context_Answer_Question",
]
c9_2e = [
    "natural_questions_open_1_0_0",
    "web_questions_whats_the_answer",
    "web_questions_question_answer",
    "dbpedia_14_pick_one_category_for_the_following_text",
    "kilt_tasks_hotpotqa_combining_facts",
    "web_questions_short_general_knowledge_q",
    "kilt_tasks_hotpotqa_straighforward_qa",
    "adversarial_qa_dbidaf_generate_question",
    "adversarial_qa_droberta_based_on",
    "web_questions_get_the_answer",
    "kilt_tasks_hotpotqa_complex_question",
    "web_questions_potential_correct_answer",
    "trivia_qa_rc_1_1_0",
    "kilt_tasks_hotpotqa_formulate",
    "adversarial_qa_dbert_based_on",
    "adversarial_qa_dbidaf_based_on",
    "squad_v1_1_3_0_0",
]
