name: "Formatter"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 20 * * 3'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Install isort
        run: |
          pip install isort==5.13.2

      - name: Run isort
        run: |
          isort --profile black --check-only --diff .
